# Define a service for theia
# TODO(jlewi): This needs to be adjusted based on kpt setters
apiVersion: v1
kind: Service
metadata:
  name: mnist-theia # {"$ref":"#/definitions/io.k8s.cli.substitutions.theia-name"}
spec:
  ports:
  - name: http-theia
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    notebook-name: mnist
  type: ClusterIP
