apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: prod
namespace: label-bot-prod
patchesStrategicMerge:
- deployments.yaml
resources:
- ../../base
images:
- name: gcr.io/issue-label-bot-dev/bot-worker
  newName: gcr.io/issue-label-bot-dev/bot-worker
  newTag: 8472f90
